# This file is machine-generated - editing it directly is not advised

[[Freeze]]
deps = ["LinearAlgebra", "SparseArrays"]
git-tree-sha1 = "d3b9dd876ec841ef75c1b1c6ec3002518c8f9e16"
repo-rev = "master"
repo-url = "../Freeze"
uuid = "5ec2d65f-4743-4a68-a0d2-9e48020e74af"
version = "0.1.0"

[[Libdl]]
uuid = "8f399da3-3557-5675-b5ff-fb832c97cbdb"

[[LinearAlgebra]]
deps = ["Libdl"]
uuid = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[[Random]]
deps = ["Serialization"]
uuid = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[[Serialization]]
uuid = "9e88b42a-f829-5b0c-bbe9-9e923198166b"

[[SparseArrays]]
deps = ["LinearAlgebra", "Random"]
uuid = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
